### ISSUE TITLE
Feature request: Variable lane width

### ISSUE THREAD

**Issue by rkarlsba** [jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box#10]
With, say, 8x8 lanes on the innermost labyrinth, it should be possible to allow for larger labyrinths on the outer ones, having a larger area to work on, meaning the outer labyrinth may be bigger and harder than the inner, smaller one

**Comment by jmerc77** [comment]
this is already in place. the outer mazes have higher density. this is auto computed based on height and diameter.
