### ISSUE TITLE
directory names should be in the ini file

### ISSUE THREAD

**Issue by rkarlsba** [jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box#4]
Seems simple enough, but I'm a bit confused of the code execution order, so I won't change anything.

By the way - what happens if files exist already? Haven't tried that yet

For parallel runs, something like a 'run name' given by an argument or something in the ini file (doesn't matter, can be changed later) could make it choose a prefix for the files. Should work

**Comment by rkarlsba** [comment]
oh - right - as for the last question, for parallel runs, the current way is to just remove all traces of other software, meaning things need to be rewritten a bit. Automatically removing what may be hours of work doesn't seem like a good idea

**Comment by jmerc77** [comment]
added a name option. for stl export folder.

**Comment by jmerc77** [comment]
did more touching up.
parallel runs still needs to be done though. work on that next.

**Comment by jmerc77** [comment]
actually, it may be not be a good idea to run parallel. might cause too many threads!

**Comment by jmerc77** [comment]
"it may be not be a good idea to run parallel" for now. so I am closing this. see above.
