### ISSUE TITLE
Feature request: Easier sliding

### ISSUE THREAD

**Issue by rkarlsba** [jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box#7]
I've built a few now, and although this works, compared to the original (https://www.thingiverse.com/thing:2607374 or others),the surface of the maze is very flat and the nubs (?) are quare-formed when seen from the top, as opposed to the pyramid-shape of those from the original. The original is very easy to use, where those from the model are trickier and I'd guess will easier lead to damaged nubs (?) because of friction.

Would it be hard to change the shape of things for them to work (and indeed look) a bit better?

thanks

roy

**Comment by jmerc77** [comment]
the new nubs are squarish as an upgrade. oddly, they last longer than the old ones! they tended to rub off to a sharp point during my tests. I used ABS.

**Comment by jmerc77** [comment]
just added oldnubs option + many fixes.
