### ISSUE TITLE
Save settings before starting a run

### ISSUE THREAD

**Issue by rkarlsba** [jmerc77/remix-of-Russian-Doll-Maze-Puzzle-Box#8]
If planning a run, and starting it, you may want start printing the first piece before the others are finished. If you do, and the build is interrupted, resuming the build (or restarting it like before) won't be possible since the random seed is lost.

If I could save everything, like seed, whatever prompted for and the contents of the ini file in a run file, it'd help a lot if I want to re-run something and have comparible results. It would also make bug reporting a bit easier

**Comment by jmerc77** [comment]
I was looking into that before vaca. still trying to get it straight.

**Comment by jmerc77** [comment]
all settings in ini now.
